### WELCOME PAGE
GET http://localhost:1503/welcome

### EASTER EGG ;p
GET http://localhost:1503/newyear

##################################
############   USER   ############
##################################

### CREATE A NEW USER
POST http://localhost:1503/user
Content-Type: application/json

{
    "name" : "DOE John",
    "email" : "john@doe.com",
    "password" : "J0hnD0e1998*",
    "dateOfBirth" : "1998-07-15",
    "passportNumber" : "USA7654321",
    "passportCountry" : "USA",
    "role" : "passenger"
}

### GET ALL USERS
GET http://localhost:1503/users

### GET A USER BY ID
GET http://localhost:1503/user/1

### UPDATE A USER BY ID
PUT http://localhost:1503/user/1
Content-Type: application/json

{
    "name" : "GRISVAL Thibault"
}

### DELETE A USER BY ID
DELETE http://localhost:1503/user/2

##################################
###########   AIRPORT  ###########
##################################

### CREATE A NEW AIRPORT
POST http://localhost:1503/airport
Content-Type: application/json

{
    "name" : "Starptautiska lidosta Riga",
    "code" : "LET001",
    "city" : "Riga",
    "country" : "LATVIA"
}

### GET ALL AIRPORTS
GET http://localhost:1503/airports

### GET ALL AIRPORTS BY COUNTRY
GET http://localhost:1503/airports?country=France

### GET AN AIRPORT BY ID
GET http://localhost:1503/airport/3

### UPDATE AN AIRPORT BY ID
PUT http://localhost:1503/airport/5
Content-Type: application/json

{
    "code" : "LAT001"
}

### DELETE AN AIRPORT BY ID
DELETE http://localhost:1503/airport/3

##################################
############  BOOKING ############
##################################

### CREATE A NEW BOOKING
POST http://localhost:1503/booking
Content-Type: application/json

{
    "flightID" : "19",
    "userId" : "04",
    "seatNumber" : "07F",
    "status" : "in flight",
    "dateBooked" : "2022-10-10"
}

### GET ALL BOOKINGS
GET http://localhost:1503/bookings

### GET A BOOKING BY ID
GET http://localhost:1503/booking/4

### UPDATE AN BOOKING BY ID
PUT http://localhost:1503/booking/5
Content-Type: application/json

{
    "seatNumber" : "11A"
}

### DELETE AN BOOKING BY ID
DELETE http://localhost:1503/booking/3

##################################
############  FLIGHTS ############
##################################

### CREATE A NEW FLIGHT
POST http://localhost:1503/flight
Content-Type: application/json

{
    "airline" : "Air France",
    "dateStart" : "2023-02-20T04:33:12.000Z",
    "dateEnd" : "2023-02-20T07:54:12.000Z",
    "origin" : "LET001",
    "arrival" : "FRA001",
    "status" : "planned",
    "capacity" : 128

}

### GET ALL FLIGHTS
GET http://localhost:1503/flights

### GET A FLIGHT BY ID
GET http://localhost:1503/flight/1

### UPDATE A FLIGHT BY ID
PUT http://localhost:1503/flight/2
Content-Type: application/json

{
    "airline" : "RyanAir"
}

### DELETE A FLIGHT BY ID
DELETE http://localhost:1503/flight/3