const { Model, DataTypes } = require("sequelize");
const database = require("./database");

class Booking extends Model {}

Booking.init({
  /*
    //The id is automatically generated by the database, so it's not necessary to create it
    id: {
        type: DataTypes.INTEGER,
        unique: true,
        primaryKey: true,
        autoIncrement: true,
    },
    */
    flightID: {
         type: DataTypes.INTEGER,
         unique: false,
         allowNull: false,
         references: 'flights',
         referencesKey: 'id'
    },
    userId: {
        type: DataTypes.INTEGER,
        references: 'users',
        referencesKey: 'id'
    },
    seatNumber: {
        type: DataTypes.INTEGER,
        unique: false,
        allowNull: false,
        validate:{
            is: /^[0-9]{0,2}[A-Z]{1}$/
        }
    },
    status: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
            isIn: [["planned", "in flight", "landed"]]
        }
    },
    dateBooked: {
        type: DataTypes.DATE,
        allowNull:false
    }
}, {
    sequelize: database,
    timestamps: false,
});

module.exports = Booking;