const { Model, DataTypes } = require("sequelize");
const database = require("./database");

class Flight extends Model { }

Flight.init({
    /*
    //The id is automatically generated by the database, so it's not necessary to create it
    id: {
        type: DataTypes.INTEGER,
        unique: true,
        primaryKey: true,
        autoIncrement: true,
    },
    */
    airline: {
        type: DataTypes.STRING,
        unique: false,
        allowNull: false,
    },
    dateStart: {
        type: DataTypes.DATE,
        unique: false,
        allowNull: false,
    },
    dateEnd: {
        type: DataTypes.DATE,
        unique: false,
        allowNull: false,
    },
    origin: {
        type: DataTypes.INTEGER,
        unique: false,
        allowNull: false,
        validate: {
            // 3 uppercase letters and 3 numbers
            is: /^[A-Z]{3}[0-9]{3}$/
        },
        references: 'airports',
        referencesKey: 'code'
    },
    arrival: {
        type: DataTypes.INTEGER,
        unique: false,
        allowNull: false,
        validate: {
            // 3 uppercase letters and 3 numbers
            is: /^[A-Z]{3}[0-9]{3}$/
        },
        references: 'airports',
        referencesKey: 'code'
    },
    status: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
            isIn: [["planned", "in flight", "landed"]]
        }
    },
    capacity: {
        type: DataTypes.INTEGER,
            unique: false,
            allowNull: false
    }
}, {
    sequelize: database,
    timestamps: false,
});

module.exports = Flight;